name: dear_diary
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.4 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  share_plus: ^10.1.4
  flutter_markdown: ^0.7.6+2
  equatable: ^2.0.7
  package_info_plus: ^8.3.0
  image_picker: ^1.1.2
  get_it: ^8.0.3
  uuid: ^4.5.1
  bloc: ^9.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
